# example config.yaml
# Maps Projects to to their build/deploy configurations
apps:
  app-01:
    build:
      repo: trevorhudson/gh-dispatch
      workflow: example-build.yml
      inputs: { app: "app-01" }
    deploy:
      repo: trevorhudson/gh-dispatch
      workflow: example-deploy.yml
      inputs: { app: "app-01" }
  app-02:
    build:
      repo: trevorhudson/gh-dispatch
      workflow: example-build.yml
    deploy:
      repo: trevorhudson/gh-dispatch
      workflow: example-deploy.yml
  app-03:
    build:
      repo: trevorhudson/gh-dispatch
      workflow: example-build.yml
    deploy:
      repo: trevorhudson/gh-dispatch
      workflow: example-deploy.yml

  # ... more projects
